### ISSUE TITLE
Errors in Setup/Proving/Verifying Phase

### ISSUE THREAD

**Issue by woopuiyung** [circify/circ#125]
I tried to use CirC (the latest version #124) to compile some ZoKrates programs, but I saw some of the following errors. 
- Error 1: Compilation error when comparing two field elements
- Error 2: Error in the proving phase of the program [isolate_assert.zok](https://github.com/circify/circ/blob/master/examples/ZoKrates/pf/isolate_assert.zok)
- Error 3: Error in the verifying phase when there is an unused public input in the program

### Error 1: Compilation error when comparing two field elements
**Sample test code (testgreaterthan.zok):**
```
def main(private field x, private field y) -> field:
    return if x > y then x  else y fi
```
**Result:**
```
$ ./target/release/examples/circ myexamples/testgreaterthan.zok r1cs --action setup
Options { path: "myexamples/testgreaterthan.zok", frontend: FrontendOptions { language: Auto, value_threshold: None, rec_limit: 5, lint_prim_rec: false, z_isolate_asserts: false }, parties: 2, backend: R1cs { prover_key: "P", verifier_key: "V", lc_elimination_thresh: 50, action: Setup } }
Done with IR optimization
Converting to r1cs
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/ubuntu/circlatest/circ/circ_fields/src/lib.rs:240:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Error 2: Error in the proving phase of the program [isolate_assert.zok](https://github.com/circify/circ/blob/master/examples/ZoKrates/pf/isolate_assert.zok)
**Sample test code [(isolate_assert.zok)](https://github.com/circify/circ/blob/master/examples/ZoKrates/pf/isolate_assert.zok):**
```
def mult(field x, field y) -> field:
    assert(x != y)
    return x * y

def main(private field x, private field y) -> field:
    return if x == y then x * x else mult(x, y) fi
```
**Prover input [(isolate_assert.zok.pin)](https://github.com/circify/circ/blob/master/examples/ZoKrates/pf/isolate_assert.zok.pin):**
```
(set_default_modulus 52435875175126190479447740508185965837690552500527637822603658699938581184513
(let (
    (x #f4)
    (y #f4)
) true ;ignored
)
)
```

**Result:**
```
$ ./target/release/examples/circ examples/ZoKrates/pf/isolate_assert.zok r1cs --action setup
Options { path: "examples/ZoKrates/pf/isolate_assert.zok", frontend: FrontendOptions { language: Auto, value_threshold: None, rec_limit: 5, lint_prim_rec: false, z_isolate_asserts: false }, parties: 2, backend: R1cs { prover_key: "P", verifier_key: "V", lc_elimination_thresh: 50, action: Setup } }
Done with IR optimization
Converting to r1cs
Pre-opt R1cs size: 7
Final R1cs size: 3
Generating Parameters
$ ./target/release/examples/zk --inputs examples/ZoKrates/pf/isolate_assert.zok.pin --action prove
Proving
thread 'main' panicked at 'Error! Bad constraint:
    +0 is_zero_inv_n5 +1 (value #f0m52435875175126190479447740508185965837690552500527637822603658699938581184513)
  * +0 y_n1 -1 x_n2 +1 (value #f0m52435875175126190479447740508185965837690552500527637822603658699938581184513)
  = +1 (value #f1m52435875175126190479447740508185965837690552500527637822603658699938581184513)', src/target/r1cs/mod.rs:365:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
### Error 3: Error in the verifying phase when there is an unused public input in the program
**Sample test code (unused_var.zok):**
```
def main(u64 x0, u64 x1, u64 x2) -> u64:
    return x0 * x1
```
**Prover Input (unused_var.zok.pin):**
```
(let (
    (x0 #x0000000000000004)
    (x1 #x0000000000000004)
    (x2 #x0000000000000000)
)
    false
)
```
**Verifier Input (unused_var.zok.vin):**
```
(let (
    (x0 #x0000000000000004)
    (x1 #x0000000000000004)
    (x2 #x0000000000000000)
    (return #x0000000000000010)
)
    false
)
```
**Result:**
```
$ ./target/release/examples/circ myexamples/unused_var.zok r1cs --action setup
Options { path: "myexamples/unused_var.zok", frontend: FrontendOptions { language: Auto, value_threshold: None, rec_limit: 5, lint_prim_rec: false, z_isolate_asserts: false }, parties: 2, backend: R1cs { prover_key: "P", verifier_key: "V", lc_elimination_thresh: 50, action: Setup } }
Done with IR optimization
Converting to r1cs
Pre-opt R1cs size: 132
Final R1cs size: 131
Generating Parameters
$ ./target/release/examples/zk --inputs myexamples/unused_var.zok.pin --action prove
Proving
$ ./target/release/examples/zk --inputs myexamples/unused_var.zok.vin --action verify
Verifying
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidVerifyingKey', /home/ubuntu/circlatest/circ/src/target/r1cs/bellman.rs:331:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Thanks for your help!

**Comment by alex-ozdemir** [comment]
I've copied my (email) response below.

Hi Anna,

> This is Anna again. I want to ask if there is any update on issue #125,

Ah! I didn't see that. Github doesn't email me when there is a new issue. In
the future, feel free to email me yourself.

> especially on errors 1 and 3, which do not happen when I run similar
> ZoKrates programs using ZoKrates toolbox. Error 1 is that I cannot compile
> ZoKrates programs that involve comparing two field elements, and error 3 is
> that unused public inputs cause errors in verifying phase. Thanks much!

Let's discuss them case-by-case.

Error 1: Yes, this is a bug, thank you! Out of curiosity, in which situation
do you perform comparisons on field elements? They are very expensive in R1CS,
and often something cheaper will do.

Error 2: This is intended behavior. In ZoKrates (default), assertions apply
even inside the un-taken case of a conditional expression.

If you would like assertions to only apply if the *taken* case, use
`--zsharp-isolate-asserts true` (as in `zokrates_test`'s `pf_test_isolate`
function). Note that we haven't tested this feature much. Let us know if you
encounter bugs.

Error 3: This is a bug, thank you!

I included your test-cases (and fixed the bugs) in [1].

Cheers,
Alex

[1]: https://github.com/circify/circ/pull/131
