### ISSUE TITLE
Supporting smtlib output?

### ISSUE THREAD

**Issue by ytrezq** [circify/circ#191]
Hello, most sat/smt solvers like z3 use the smtlib format with sometimes extensions like the very efficient cryptominisat that support xor.

This would to use solver implementations running on fpga.

**Comment by alex-ozdemir** [comment]
[This function](https://github.com/circify/circ/blob/master/src/target/smt/mod.rs#L346) writes an IR `Term` as and SMT-LIB2 string. Perhaps that is what you're looking for?
