### ISSUE TITLE
How to compile circom to ꜱᴍᴛ ?

### ISSUE THREAD

**Issue by ytrezq** [circify/circ#192]
Simple question… Is it impossible because it can only compile to R1ᴄꜱ ?

**Comment by ytrezq** [comment]
@alex-ozdemir Hemm no : the mainstram tools I want to use like ccv5 that have plugins to work on ʜʙᴍ2 ꜰᴘɢᴀ are only compatible with ꜱᴍᴛlib.

Are there plans to add circom support again in the future ? Cirv1 only supported ʀ1ᴄꜱ…

**Comment by alex-ozdemir** [comment]
> Are there plans to add circom support again in the future ? Circv1 only supported ʀ1ᴄꜱ…

I'm not planning on doing this right now. Of course, if someone wanted to write such a front-end and develop good enough tests, I'd be happy to merge it.

**Comment by ytrezq** [comment]
@alex-ozdemir : what about converting ʀ1ᴄꜱ to ꜱᴍᴛ ?

**Comment by alex-ozdemir** [comment]
As noted [here](https://github.com/circify/circ/issues/191), CirC has machinery to output IR as SMT. If you add machinery to parse your R1CS as CirC IR, then you would be able to do this.
