### ISSUE TITLE
Brief licensing query

### ISSUE THREAD

**Issue by cwgoes** [circify/circ#24]
Hello! We've been taking a look at [your paper](https://eprint.iacr.org/2020/1586.pdf) and might be interested in contributing, if that's possible. Do you plan to license this project as OSS? I looked for a LICENSE file but didn't find one (though perhaps I missed it). Thanks!

**Comment by 42ndTowel** [comment]
Fixed by 8a9f294d8db408f14efe0aec9058b8f3fea74881 🙌🏿

**Comment by kwantam** [comment]
Closing as fixed. Please reopen if there's more to do here!
