### ISSUE TITLE
moduli and types for field elements

### ISSUE THREAD

**Issue by kwantam** [circify/circ#31]
As @alex-ozdemir has noted elsewhere, one thing we eventually want to clean up is the way field elements are handled. This thread is intended to kick off a discussion of how we want to do that. Very brief background (I'm sure Alex can add a lot more info here):

Right now, we use `rug::Integer` values for field types. Unfortunately, they are not super fast for modular arithmetic, which is a problem we'd like to solve.

One thing we could do is fix a field-specific type in the IR at (CirC) compile time. That gives us speed, but not convenience. Note, however, that the Z# front-end fixes the modulus at compile time anyway, so it wouldn't materially change things convenience-wise to switch to field-specific types, at least for this front-end (but of course it would be much faster!).

A related option is to make the IR agnostic to field types, by writing down (or borrowing) traits that capture the functionality we need, and having the front-end decide what concrete type implements those traits. (I bet we could just use the `ff` traits for this, and in principle we could wrap `rug::Integer` values in a thin shim to get runtime modulus selection for front-ends that want it.) The negative way of looking at this is that it kicks the can to the front-end. The more positive way to look at it is that it gives front-ends the opportunity to optimize themselves for particular fields! I'd bet that in many cases the optimization is more important than runtime modulus flexibility...

One other option that's worth mentioning: we might look into how fast a modulus-flexible field library we could build, on the assumption that *for a given value* you wouldn't change the modulus very often. This would let us keep values in Montgomery form (almost) all the time, which gives a nice speed-up, but doesn't go all the way to requiring compile-time modulus selection. This option is compatible with the one directly above, in the sense that we could have this library implement the trait(s) that the IR requires and then plug this new library in (only?) when modulus flexibility is required.

**Comment by kwantam** [comment]
I should say: I think it would be fun to work on the flexible-modulus stuff! Just not sure I have time immediately.

**Comment by alex-ozdemir** [comment]
One comment:

We don't need to take the same approach for both the IR and the R1CS target. That is, we could bind the R1CS target's field at compile time but keep using rug/GMP in the IR. This avoids sprinkling generics through the IR. It may also achieve the perf that we want; see the attached flamegraph. A small modular reduction bottleneck is visible in R1CS optimization, but not in IR optimization.
![flamegraph](https://user-images.githubusercontent.com/5809398/145875479-f01b524f-35e0-41bf-823e-5aeeb27b64ec.jpeg)
