### ISSUE TITLE
with_indices: is this doing anything?

### ISSUE THREAD

**Issue by kwantam** [circify/circ#36]
https://github.com/circify/circ/blob/a9fd7888c43d01913721fd98374775a21af71754/src/front/zokrates/term.rs#L187-L193

@alex-ozdemir quick question about the above: am I missing something here? It seems like `with_indices` gets computed as `(index, value)` tuples, and then the indices are immediately thrown away. Is there a reason to do this?

(I don't care about the efficiency, I'm just worried that either I'm missing something or there was supposed to be some other code here that is missing...)

**Comment by alex-ozdemir** [comment]
I believe that this is sorting the terms by field order created by the `FieldList` constructor. Perhaps it would be better to use https://doc.rust-lang.org/std/primitive.slice.html#method.sort_by_cached_key.

**Comment by alex-ozdemir** [comment]
The BTree is probably left over from some previous version of the code...

**Comment by kwantam** [comment]
Ah, no, I see. Me dumb.

The point is that using BTreeMap guarantees that `with_indices.into_iter()` returns values in index order. I think it would also work to just say `with_indices.into_values().collect()` on line 192, though.

Thanks for the confessional debugging :)

**Comment by kwantam** [comment]
or, as an obnoxious one-liner,

```rust
ir_terms.into_iter()
    .map(|(name, t)| (field_ty_list.search(&name).unwrap().0, t))
    .collect::<BTreeMap<_,_>>()
    .into_values()
    .collect()
```
