### ISSUE TITLE
OOB array access semantics

### ISSUE THREAD

**Issue by kwantam** [circify/circ#37]
https://github.com/circify/circ/blob/a9fd7888c43d01913721fd98374775a21af71754/src/ir/term/mod.rs#L673-L676

@alex-ozdemir 

IR OOB access semantics are "return the default for the array's value type", right? And if so, does this mean that if we want different semantics in a given language, the front-end needs to insert its own bounds checks?

(Or maybe I'm missing something obvious... again :) )

**Comment by alex-ozdemir** [comment]
> IR OOB access semantics are "return the default for the array's value type", right?

Yes.

> And if so, does this mean that if we want different semantics in a given language, the front-end needs to insert its own bounds checks?

Also yes.

It also might be reasonable to fold this into `circify`.

**Comment by kwantam** [comment]
Cool.

Note that we can implement this essentially for free with the memory checking approach to RAM, just by adding two checks to the address-ordered transcript (first accessed address >= 0, last accessed address < ram_size).

I kind of wonder if it wouldn't be worthwhile to always enforce this. Otherwise, array semantics are slightly surprising, which could lead to subtle bugs.

**Comment by alex-ozdemir** [comment]
I think that putting that kind of guarantee into the array pass would be reasonable. Probably configurably.

**Comment by kwantam** [comment]
I probably don't quite understand what you're saying, but the change might not be confined to the array pass.

I'm thinking specifically of constant folding, which (in my branch) operates on `Op::Select` and right now happily reads out of bounds.

(I have a good reason for constant folding everything, I promise! Basically, it occurred to me that, because CirC inlines everything everywhere, with a sufficiently powerful constant-folding pass we can essentially get an interpreter "for free" for any front-end language, and we get a pretty strong guarantee about the consistency of the compilation and interpretation semantics by doing this.)

For now I could just make constant folding blow up on oob access. But maybe there's a nicer way. I'll think more about it.

**Comment by kwantam** [comment]
I looked at this a little more.

Seems like one way to enforce this in the IR is to make Value::select and Value::store panic if they get an out of bounds index. In my branch I've actually already added a panic for the case where the index Sort (or, for store, value Sort) is wrong---so as long as you don't object to that, this wouldn't be totally crazy.

Maybe even better would be to make these functions return `Result<_, _>`, since that would presumably make for nicer error reporting during compilation.

But as I looked into it, I noticed that there's a bit of a problem. Right now `key_sort` is unrestricted (this is slightly weird to me---does it make sense to have an index of `Sort::Tuple` or `Sort::Array`, or even `Sort::F32` or `Sort::F64`?), which means that there's no way to check, say, in `Array::select` whether a given index is in-bounds!

One way to make this work would be to restrict `Sort` to integral-ish types, and to replace `Array::size` with `Array::min_idx` and `Array::max_idx`. Does that seem reasonable?

By the way, a related (but somewhat simpler) issue arises with Tuples, though I'm guessing in this case accessing an oob index in a tuple would just result in a compiler panic.

---

I also thought a bit more about whether this really does belong in the IR, and it seems to me like it *does*, because leaving it to the front-end dramatically increases the cost of enforcing in-bounds access when lowering to R1CS. But maybe there's reason to think otherwise, too!

**Comment by alex-ozdemir** [comment]
> interpreter "for free" for any front-end language

Great observation. Very cool.

We could write some powerful testing machinery using this.

> Right now Array::key_sort is unrestricted 

Yes, as you say, it should be restricted. I'd put the restriction in the
type-checker too. It should be restricted to the sorts supported here[1].

> making Array::new a partial function

Good idea.

> replace Array::size with Array::min_idx and Array::max_idx

Do you know of situations where non-zero min_idx values would be useful?

> a related (but somewhat simpler) issue arises with Tuples

Yes. It wouldn't type-check.

[1]: https://github.com/circify/circ/blob/master/src/ir/term/mod.rs#L793-L796

**Comment by kwantam** [comment]
> Do you know of situations where non-zero min_idx values would be useful?

No. The issue is that `Value::Int` can take negative values. But I suppose we can just detect that case and blow up, probably.

**Comment by kwantam** [comment]
OK, I've pushed the simplest possible oob enforcement for the IR: 7470480

Of course, this doesn't change anything about the back-end semantics for IR arrays! Enforcing OOB checks in R1CS is pretty easy and cheap (both naively and for the permutation-based RAM approach), but I'm not sure about other back-ends. @alex-ozdemir, thoughts? I'm happy to make changes here as necessary...

**Comment by kwantam** [comment]
Ah, by the way: I thought this over and couldn't come up with a case where we'd want the "return default value" semantics instead of the "throw an error" semantics. But this could be a failure of imagination. Thoughts?

**Comment by alex-ozdemir** [comment]
> No. The issue is that Value::Int can take negative values. But I suppose we
> can just detect that case and blow up, probably. Or not allow Int indices...

Yeah, I think we should always take 0 as the minimum index for now. We can
generalize later.

> Ah, by the way: I thought this over and couldn't come up with a case where
> we'd want the "return default value" semantics instead of the "throw an
> error" semantics. But this could be a failure of imagination. Thoughts?

I want to think about this a little more.

I agree when it comes to ZKPs: the only situation that comes to mind at all is
the linear scan IR pass. But even there, there is an efficient way to render
the circuit UNSAT on a bad index.

I need to think about MPC though... We don't have a good notion of "crashing"
the MPC. Having total semantics seems more useful for that kind of target...

**Comment by kwantam** [comment]
Ah, right. #30 altered oob semantics. I think we discussed this on Zoom at some point and decided to go ahead with it. (...right?)

Since we're passing the tests I guess this means the C front-end didn't break as a result of this change (as one would hope!).

So, closing for now. But we can re-open if we need to discuss.
