### ISSUE TITLE
PfToBv: only defined for field elms in 0,1?

### ISSUE THREAD

**Issue by kwantam** [circify/circ#61]
https://github.com/circify/circ/blob/0d61d45a6594a63324c44286afa01bf414a5e490/src/ir/term/mod.rs#L1335-L1339

Am I reading this correctly? Is this assert necessary?

**Comment by kwantam** [comment]
@alex-ozdemir maybe the intent was to make sure that `a.i() < 1 << w`?

**Comment by alex-ozdemir** [comment]
!! Yes, thank you.

Here: https://github.com/circify/circ/pull/62

**Comment by kwantam** [comment]
This was fixed in #66
