### ISSUE TITLE
Incorrect version of ZoKrates in README

### ISSUE THREAD

**Issue by collinzrj** [circify/circ#99]
https://github.com/circify/circ/blob/4686854248485f59088898832bff78b3a184a0e2/third_party/README.md?plain=1#L5-L7
In the README.md of third_party, the version of ZoKrates is 0.6.3, but according to https://github.com/circify/circ/pull/30, the version of ZoKrates has been updated to 0.7.6

**Comment by alex-ozdemir** [comment]
Thanks for reporting this, it has been fixed.
